//! Reversible, marker-guarded supervisor units for continuous ingestion.
//!
//! This is the second out-of-database filesystem artifact `autophagy-install`
//! owns (see ADR 0008). A supervisor unit tells the platform init system to run
//! `autophagy watch` in the background. Generation is deterministic; writing
//! refuses to clobber a file Autophagy did not author, and removal refuses to
//! delete a foreign file — the same discipline the repo-scoped skill materializer
//! already enforces.
//!
//! The watch process it launches only ingests: it never executes, installs, or
//! acts on evidence, so this adds no autonomous execution capability.

use std::{
    fmt::Write as _,
    fs::{self, OpenOptions},
    io::Write as _,
    path::{Path, PathBuf},
};

/// Stable launchd/label identity for the watch job.
pub const WATCH_LABEL: &str = "sh.autophagy.watch";

/// Marker embedded in every generated unit so Autophagy can recognise its own
/// files and refuse to touch foreign ones.
pub const MANAGED_MARKER: &str = "managed-by: sh.autophagy.watch";

/// Platform supervisor flavour.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SupervisorKind {
    /// macOS launchd user agent (`~/Library/LaunchAgents/*.plist`).
    Launchd,
    /// Linux systemd user unit (`~/.config/systemd/user/*.service`).
    Systemd,
}

impl SupervisorKind {
    /// Unit file name for this flavour.
    #[must_use]
    pub const fn file_name(self) -> &'static str {
        match self {
            Self::Launchd => "sh.autophagy.watch.plist",
            Self::Systemd => "autophagy-watch.service",
        }
    }
}

/// Everything needed to render one supervisor unit.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SupervisorConfig {
    /// Supervisor flavour to render.
    pub kind: SupervisorKind,
    /// Directory the unit is written into (e.g. `~/Library/LaunchAgents`).
    pub unit_directory: PathBuf,
    /// Absolute path to the `autophagy` binary.
    pub binary_path: PathBuf,
    /// Seconds between watch cycles.
    pub interval_secs: u64,
    /// Native adapters passed to `watch --adapter`; empty means the binary's
    /// own default (all native adapters).
    pub adapters: Vec<String>,
    /// Optional explicit database path.
    pub database: Option<PathBuf>,
    /// Standard-output log destination.
    pub log_path: PathBuf,
    /// Standard-error log destination.
    pub error_log_path: PathBuf,
}

/// Deterministic rendered unit plus the exact command line it launches.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SupervisorPlan {
    /// Supervisor flavour.
    pub kind: SupervisorKind,
    /// Job label / identity.
    pub label: String,
    /// Absolute path the unit is written to.
    pub unit_path: PathBuf,
    /// Full argument vector, argv[0] first.
    pub program_arguments: Vec<String>,
    /// Complete rendered unit contents.
    pub content: String,
}

/// Build the argument vector `autophagy watch …` from a config.
fn program_arguments(config: &SupervisorConfig) -> Vec<String> {
    let mut arguments = vec![config.binary_path.to_string_lossy().into_owned()];
    if let Some(database) = &config.database {
        arguments.push("--database".to_owned());
        arguments.push(database.to_string_lossy().into_owned());
    }
    arguments.push("watch".to_owned());
    arguments.push("--interval".to_owned());
    arguments.push(config.interval_secs.to_string());
    for adapter in &config.adapters {
        arguments.push("--adapter".to_owned());
        arguments.push(adapter.clone());
    }
    arguments
}

/// Render a deterministic supervisor plan without writing anything.
#[must_use]
pub fn plan_supervisor(config: &SupervisorConfig) -> SupervisorPlan {
    let arguments = program_arguments(config);
    let unit_path = config.unit_directory.join(config.kind.file_name());
    let content = match config.kind {
        SupervisorKind::Launchd => render_launchd(&arguments, config),
        SupervisorKind::Systemd => render_systemd(&arguments, config),
    };
    SupervisorPlan {
        kind: config.kind,
        label: WATCH_LABEL.to_owned(),
        unit_path,
        program_arguments: arguments,
        content,
    }
}

fn render_launchd(arguments: &[String], config: &SupervisorConfig) -> String {
    let mut rendered = String::new();
    rendered.push_str("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
    let _ = writeln!(
        rendered,
        "<!-- {MANAGED_MARKER} — generated by `autophagy daemon install`; do not edit by hand -->"
    );
    rendered.push_str(
        "<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n",
    );
    rendered.push_str("<plist version=\"1.0\">\n<dict>\n");
    let _ = writeln!(
        rendered,
        "    <key>Label</key>\n    <string>{WATCH_LABEL}</string>"
    );
    rendered.push_str("    <key>ProgramArguments</key>\n    <array>\n");
    for argument in arguments {
        let _ = writeln!(
            rendered,
            "        <string>{}</string>",
            xml_escape(argument)
        );
    }
    rendered.push_str("    </array>\n");
    rendered.push_str("    <key>RunAtLoad</key>\n    <true/>\n");
    rendered.push_str("    <key>KeepAlive</key>\n    <true/>\n");
    rendered.push_str("    <key>ProcessType</key>\n    <string>Background</string>\n");
    let _ = writeln!(
        rendered,
        "    <key>StandardOutPath</key>\n    <string>{}</string>",
        xml_escape(&config.log_path.to_string_lossy())
    );
    let _ = writeln!(
        rendered,
        "    <key>StandardErrorPath</key>\n    <string>{}</string>",
        xml_escape(&config.error_log_path.to_string_lossy())
    );
    rendered.push_str("</dict>\n</plist>\n");
    rendered
}

fn render_systemd(arguments: &[String], config: &SupervisorConfig) -> String {
    let exec_start = arguments
        .iter()
        .map(|argument| shell_quote(argument))
        .collect::<Vec<_>>()
        .join(" ");
    let mut rendered = String::new();
    let _ = writeln!(
        rendered,
        "# {MANAGED_MARKER} — generated by `autophagy daemon install`; do not edit by hand"
    );
    rendered.push_str("[Unit]\n");
    rendered.push_str("Description=Autophagy continuous ingestion (watch)\n");
    rendered.push_str("After=default.target\n\n");
    rendered.push_str("[Service]\n");
    rendered.push_str("Type=simple\n");
    let _ = writeln!(rendered, "ExecStart={exec_start}");
    rendered.push_str("Restart=on-failure\n");
    rendered.push_str("RestartSec=5\n");
    let _ = writeln!(
        rendered,
        "StandardOutput=append:{}",
        config.log_path.to_string_lossy()
    );
    let _ = writeln!(
        rendered,
        "StandardError=append:{}",
        config.error_log_path.to_string_lossy()
    );
    rendered.push('\n');
    rendered.push_str("[Install]\n");
    rendered.push_str("WantedBy=default.target\n");
    rendered
}

/// Whether the given unit contents were generated by Autophagy.
#[must_use]
pub fn is_managed(content: &str) -> bool {
    content.contains(MANAGED_MARKER)
}

/// Write the planned unit, creating the target directory if necessary.
///
/// An existing unit is overwritten only when it carries the Autophagy marker
/// (idempotent reinstall); a file Autophagy did not author is never touched.
///
/// # Errors
/// Returns [`SupervisorError::ForeignFile`] when the target exists but is not
/// managed by Autophagy, or [`SupervisorError::Io`] on a filesystem failure.
pub fn write_supervisor(plan: &SupervisorPlan) -> Result<(), SupervisorError> {
    if let Some(parent) = plan.unit_path.parent() {
        fs::create_dir_all(parent)?;
    }
    match fs::read_to_string(&plan.unit_path) {
        Ok(existing) if !is_managed(&existing) => {
            return Err(SupervisorError::ForeignFile(plan.unit_path.clone()));
        }
        Ok(_) => {}
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
        Err(error) => return Err(error.into()),
    }
    let mut file = OpenOptions::new()
        .write(true)
        .create(true)
        .truncate(true)
        .open(&plan.unit_path)?;
    file.write_all(plan.content.as_bytes())?;
    file.sync_all()?;
    Ok(())
}

/// Remove a supervisor unit Autophagy authored.
///
/// Returns `true` when a file was removed, `false` when nothing was present.
///
/// # Errors
/// Returns [`SupervisorError::ForeignFile`] when the target exists but is not
/// managed by Autophagy, or [`SupervisorError::Io`] on a filesystem failure.
pub fn remove_supervisor(unit_path: &Path) -> Result<bool, SupervisorError> {
    match fs::read_to_string(unit_path) {
        Ok(existing) if !is_managed(&existing) => {
            Err(SupervisorError::ForeignFile(unit_path.to_path_buf()))
        }
        Ok(_) => {
            fs::remove_file(unit_path)?;
            Ok(true)
        }
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(false),
        Err(error) => Err(error.into()),
    }
}

fn xml_escape(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}

fn shell_quote(value: &str) -> String {
    if value
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || matches!(c, '/' | '.' | '-' | '_' | ':' | '='))
    {
        value.to_owned()
    } else {
        format!("\"{}\"", value.replace('\\', "\\\\").replace('"', "\\\""))
    }
}

/// Error produced while writing or removing a supervisor unit.
#[derive(Debug, thiserror::Error)]
pub enum SupervisorError {
    /// The target exists but was not authored by Autophagy.
    #[error("supervisor unit '{}' was not written by Autophagy; refusing to overwrite it", .0.display())]
    ForeignFile(PathBuf),
    /// Filesystem operation failed.
    #[error("supervisor filesystem operation failed: {0}")]
    Io(#[from] std::io::Error),
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_config(kind: SupervisorKind, directory: PathBuf) -> SupervisorConfig {
        SupervisorConfig {
            kind,
            unit_directory: directory,
            binary_path: PathBuf::from("/opt/autophagy/bin/autophagy"),
            interval_secs: 60,
            adapters: vec!["claude-code".to_owned(), "codex".to_owned()],
            database: None,
            log_path: PathBuf::from("/home/user/.local/share/Autophagy/watch.log"),
            error_log_path: PathBuf::from("/home/user/.local/share/Autophagy/watch.err.log"),
        }
    }

    #[test]
    fn launchd_plist_is_deterministic() {
        let config = sample_config(SupervisorKind::Launchd, PathBuf::from("/agents"));
        let plan = plan_supervisor(&config);
        let expected = [
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?>",
            "<!-- managed-by: sh.autophagy.watch — generated by `autophagy daemon install`; do not edit by hand -->",
            "<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">",
            "<plist version=\"1.0\">",
            "<dict>",
            "    <key>Label</key>",
            "    <string>sh.autophagy.watch</string>",
            "    <key>ProgramArguments</key>",
            "    <array>",
            "        <string>/opt/autophagy/bin/autophagy</string>",
            "        <string>watch</string>",
            "        <string>--interval</string>",
            "        <string>60</string>",
            "        <string>--adapter</string>",
            "        <string>claude-code</string>",
            "        <string>--adapter</string>",
            "        <string>codex</string>",
            "    </array>",
            "    <key>RunAtLoad</key>",
            "    <true/>",
            "    <key>KeepAlive</key>",
            "    <true/>",
            "    <key>ProcessType</key>",
            "    <string>Background</string>",
            "    <key>StandardOutPath</key>",
            "    <string>/home/user/.local/share/Autophagy/watch.log</string>",
            "    <key>StandardErrorPath</key>",
            "    <string>/home/user/.local/share/Autophagy/watch.err.log</string>",
            "</dict>",
            "</plist>",
            "",
        ]
        .join("\n");
        assert_eq!(plan.content, expected);
        assert_eq!(
            plan.unit_path,
            PathBuf::from("/agents/sh.autophagy.watch.plist")
        );
        assert!(is_managed(&plan.content));
    }

    #[test]
    fn systemd_unit_is_deterministic() {
        let config = sample_config(SupervisorKind::Systemd, PathBuf::from("/units"));
        let plan = plan_supervisor(&config);
        let expected = [
            "# managed-by: sh.autophagy.watch — generated by `autophagy daemon install`; do not edit by hand",
            "[Unit]",
            "Description=Autophagy continuous ingestion (watch)",
            "After=default.target",
            "",
            "[Service]",
            "Type=simple",
            "ExecStart=/opt/autophagy/bin/autophagy watch --interval 60 --adapter claude-code --adapter codex",
            "Restart=on-failure",
            "RestartSec=5",
            "StandardOutput=append:/home/user/.local/share/Autophagy/watch.log",
            "StandardError=append:/home/user/.local/share/Autophagy/watch.err.log",
            "",
            "[Install]",
            "WantedBy=default.target",
            "",
        ]
        .join("\n");
        assert_eq!(plan.content, expected);
        assert_eq!(
            plan.unit_path,
            PathBuf::from("/units/autophagy-watch.service")
        );
    }

    #[test]
    fn database_override_is_threaded_before_the_subcommand() {
        let mut config = sample_config(SupervisorKind::Systemd, PathBuf::from("/units"));
        config.database = Some(PathBuf::from("/tmp/demo.db"));
        let plan = plan_supervisor(&config);
        assert!(plan.content.contains(
            "ExecStart=/opt/autophagy/bin/autophagy --database /tmp/demo.db watch --interval 60"
        ));
    }

    #[test]
    fn write_then_remove_round_trips() {
        let dir = tempfile::tempdir().expect("temp dir");
        let config = sample_config(SupervisorKind::Launchd, dir.path().join("LaunchAgents"));
        let plan = plan_supervisor(&config);

        write_supervisor(&plan).expect("write");
        assert!(plan.unit_path.exists());
        // Idempotent re-write over our own marker file.
        write_supervisor(&plan).expect("rewrite");

        assert!(remove_supervisor(&plan.unit_path).expect("remove"));
        assert!(!plan.unit_path.exists());
        // Removing again is a no-op.
        assert!(!remove_supervisor(&plan.unit_path).expect("remove-again"));
    }

    #[test]
    fn refuses_to_overwrite_a_foreign_file() {
        let dir = tempfile::tempdir().expect("temp dir");
        let config = sample_config(SupervisorKind::Launchd, dir.path().to_path_buf());
        let plan = plan_supervisor(&config);
        fs::write(&plan.unit_path, "<plist>someone else's file</plist>\n").expect("seed");

        let error = write_supervisor(&plan).expect_err("must refuse");
        assert!(matches!(error, SupervisorError::ForeignFile(_)));

        let error = remove_supervisor(&plan.unit_path).expect_err("must refuse");
        assert!(matches!(error, SupervisorError::ForeignFile(_)));
        // The foreign file is left untouched.
        assert_eq!(
            fs::read_to_string(&plan.unit_path).expect("still there"),
            "<plist>someone else's file</plist>\n"
        );
    }

    #[test]
    fn xml_escapes_special_characters_in_paths() {
        let mut config = sample_config(SupervisorKind::Launchd, PathBuf::from("/agents"));
        config.log_path = PathBuf::from("/home/a & b/watch.log");
        let plan = plan_supervisor(&config);
        assert!(plan.content.contains("/home/a &amp; b/watch.log"));
    }
}
